export { default as Button } from '@vtex/styleguide/lib/Button'
export { default as Dropdown } from '@vtex/styleguide/lib/Dropdown'
export { default as Input } from '@vtex/styleguide/lib/Input'
export { default as Link } from '@vtex/styleguide/lib/Link'
export { default as Spinner } from '@vtex/styleguide/lib/Spinner'
export { default as IconDelete } from '@vtex/styleguide/lib/icon/Delete'
